"""
The trust layer. Fetches real prices via direct HTTP, no yfinance, no pandas-datareader.
  - Equities / ETFs / Indices : Twelve Data /time_series (batch, free tier 800/day)
  - VIX                       : Twelve Data (avoids FRED T+1 publish lag)
  - 10Y yield + macro series  : FRED API (free key)
NOTHING here is generated by an LLM.

Required env vars:
  TWELVEDATA_API_KEY  - free at https://twelvedata.com
  FRED_API_KEY        - free at https://fred.stlouisfed.org/docs/api/api_key.html
"""

import datetime, logging, math, os, time
import numpy as np
import pandas as pd
import requests

from config import (
    INDICES, TNX, SPOTLIGHTS, WATCHLIST_AI,
    SECTOR_ETFS, CONFIG, BASE_DIR, all_tickers,
)

log        = logging.getLogger(__name__)
MKT        = "SPY"
CACHE_FILE = os.path.join(BASE_DIR, "..", "frontend", "reports", "closes_cache.pkl")
TD_BASE    = "https://api.twelvedata.com"

# only ^TNX stays on FRED; VIX moved to Twelve Data to avoid FRED T+1 publish lag
FRED_MAP = {
    # "^TNX": "DGS10",
}

# internal symbol -> Twelve Data symbol (caret prefix not accepted by TD)
TD_ALIAS = {
    "^VIX": "VIX",
    "^TNX": "TNX"
}

# macro indicators fetched from FRED separately from price tickers
MACRO_FRED_MAP = {
    "T10Y2Y":    "T10Y2Y",    # 2Y/10Y yield spread
    "T5YIEM":    "T5YIEM",    # 5Y TIPS breakeven inflation
    "T10YIEM":   "T10YIEM",   # 10Y TIPS breakeven inflation
    "SOFR":      "SOFR",      # SOFR overnight rate
    "DXY_BROAD": "DTWEXBGS",  # Broad USD index (weekly frequency)
    "FF_LOWER":  "DFEDTARL",  # Fed Funds target lower bound
    "FF_UPPER":  "DFEDTARU",  # Fed Funds target upper bound
}

_SESSION = requests.Session()
_SESSION.headers.update({"User-Agent": "Mozilla/5.0 (compatible; market-report/1.0)"})


def get_market_context() -> dict:
    # after-close report; last_trading_day < today always
    today = datetime.date.today()
    fmt   = lambda d: d.strftime("%A, %B %d, %Y")
    try:
        import pandas_market_calendars as mcal
        nyse  = mcal.get_calendar("NYSE")
        sched = nyse.schedule(
            start_date=(today - datetime.timedelta(days=10)).isoformat(),
            end_date=today.isoformat(),
        )
        days = [d.date() for d in sched.index]
        past = [d for d in days if d < today]
        ltd  = past[-1] if past else today - datetime.timedelta(days=1)
    except Exception as e:
        log.warning(f"market calendar fallback ({e})")
        wd  = today.weekday()
        ltd = today - datetime.timedelta(days={0: 3, 6: 2, 5: 1}.get(wd, 1))

    ctx = f"Today is {fmt(today)}. Report covers last completed US session: {fmt(ltd)}."
    return {
        "today": fmt(today), "last_trading_day": fmt(ltd),
        "last_trading_day_iso": ltd.isoformat(),
        "market_open": False, "context": ctx,
        "month_year": ltd.strftime("%B %Y"), "year": ltd.strftime("%Y"),
    }


# ---- Twelve Data batch fetch ----------------------------------------------
def _td_fetch_batch(symbols: list, start: datetime.date, end: datetime.date, td_key: str) -> dict:
    """Fetch daily closes in chunks of 8, free tier limit is 8 credits/minute."""
    CHUNK  = 8
    PAUSE  = 61
    frames = {}
    chunks = [symbols[i:i+CHUNK] for i in range(0, len(symbols), CHUNK)]

    for idx, chunk in enumerate(chunks):
        if idx > 0:
            log.info(f"TD rate-limit pause {PAUSE}s before chunk {idx+1}/{len(chunks)}")
            time.sleep(PAUSE)

        params = {
            "symbol":     ",".join(chunk),
            "interval":   "1day",
            "start_date": start.isoformat(),
            "end_date":   end.isoformat(),
            "outputsize": 365,
            "apikey":     td_key,
            "format":     "JSON",
        }
        try:
            r = _SESSION.get(f"{TD_BASE}/time_series", params=params, timeout=30)
            r.raise_for_status()
            j = r.json()
        except Exception as e:
            log.warning(f"TD chunk {idx+1} failed: {e}")
            continue

        if len(chunk) == 1:
            j = {chunk[0]: j}

        for sym, data in j.items():
            if isinstance(data, dict) and data.get("status") == "error":
                log.warning(f"TD error for {sym}: {data.get('message','')}")
                continue
            values = data.get("values") if isinstance(data, dict) else None
            if not values:
                log.warning(f"TD: no values for {sym}")
                continue
            try:
                s = (
                    pd.DataFrame(values)
                    .assign(datetime=lambda d: pd.to_datetime(d["datetime"]))
                    .set_index("datetime")["close"]
                    .astype(float)
                    .sort_index()
                    .rename(sym)
                )
                frames[sym] = s
            except Exception as e:
                log.warning(f"TD parse failed {sym}: {e}")

    return frames


# ---- FRED fetch -----------------------------------------------------------
def _fred_fetch(internal_sym: str, fred_id: str,
                start: datetime.date, end: datetime.date) -> pd.Series | None:
    api_key = os.getenv("FRED_API_KEY", "")
    url = (
        f"https://api.stlouisfed.org/fred/series/observations"
        f"?series_id={fred_id}"
        f"&observation_start={start.isoformat()}"
        f"&observation_end={end.isoformat()}"
        f"&file_type=json"
        + (f"&api_key={api_key}" if api_key else "")
    )
    for attempt in range(3):
        try:
            r = _SESSION.get(url, timeout=30)
            r.raise_for_status()
            obs = r.json().get("observations", [])
            if not obs:
                log.warning(f"FRED: no observations for {fred_id}")
                return None
            return (
                pd.DataFrame(obs)
                .replace(".", float("nan"))
                .assign(date=lambda d: pd.to_datetime(d["date"]))
                .set_index("date")["value"]
                .astype(float)
                .dropna()
                .sort_index()
                .rename(internal_sym)
            )
        except Exception as e:
            log.warning(f"FRED attempt {attempt+1} failed {internal_sym} ({fred_id}): {e}")
            if attempt < 2:
                time.sleep(10)
    return None


# ---- Main fetch with retry + cache ----------------------------------------
def fetch_closes(period_days: int = 365) -> pd.DataFrame:
    td_key  = os.getenv("TWELVEDATA_API_KEY", "")
    if not td_key:
        log.warning("TWELVEDATA_API_KEY not set")

    end     = datetime.date.today()
    start   = end - datetime.timedelta(days=period_days + 10)
    tickers = all_tickers()

    # symbols going to TD: everything not on FRED; translate aliases
    td_syms   = [t for t in tickers if t not in FRED_MAP]
    td_req    = [TD_ALIAS.get(t, t) for t in td_syms]
    inv_alias = {v: k for k, v in TD_ALIAS.items()}

    last_exc = None

    for attempt in range(3):
        if attempt > 0:
            wait = 30 * attempt
            log.info(f"Retrying in {wait}s (attempt {attempt+1}/3)")
            time.sleep(wait)
        try:
            frames = {}

            # TD: equities, ETFs, VIX (aliased)
            raw_td = _td_fetch_batch(td_req, start, end, td_key)
            for sym, s in raw_td.items():
                internal = inv_alias.get(sym, sym)
                frames[internal] = s.rename(internal)

            # FRED: 10Y yield
            for yahoo_sym, fred_id in FRED_MAP.items():
                s = _fred_fetch(yahoo_sym, fred_id, start, end)
                if s is not None:
                    frames[yahoo_sym] = s

            # FRED: macro indicators (separate from price tickers)
            for internal, fred_id in MACRO_FRED_MAP.items():
                s = _fred_fetch(internal, fred_id, start, end)
                if s is not None:
                    frames[internal] = s

            if not frames:
                raise RuntimeError("No data returned from Twelve Data or FRED")

            closes = pd.DataFrame(frames).sort_index()
            closes.to_pickle(CACHE_FILE)
            log.info(f"Fetched {closes.shape[1]}/{len(tickers)} tickers x {closes.shape[0]} days")
            return closes
        except Exception as e:
            last_exc = e
            log.warning(f"Fetch attempt {attempt+1} failed: {e}")

    if os.path.exists(CACHE_FILE):
        log.warning("All fetch attempts failed, loading cached closes")
        cached = pd.read_pickle(CACHE_FILE)
        log.info(f"Cache loaded: {cached.shape[1]} tickers, last date {cached.index[-1].date()}")
        return cached

    raise RuntimeError(f"No data and no cache: {last_exc}")


# ---- Core metrics ---------------------------------------------------------
def _pct(now, then):
    if then in (None, 0) or now is None or (isinstance(then, float) and math.isnan(then)):
        return None
    return round((now / then - 1) * 100, 2)


def _nth_ago(series, n):
    s = series.dropna()
    return s.iloc[-(n + 1)] if len(s) > n else None


def metrics_for(series: pd.Series) -> dict:
    s = series.dropna()
    if len(s) < 2:
        return {}
    last, prev = float(s.iloc[-1]), float(s.iloc[-2])
    rets  = s.pct_change().dropna().values
    sigma = float(np.std(rets)) if len(rets) else 0.0
    pos   = CONFIG["var_position"]
    return {
        "price":          round(last, 2),
        "day_change":     _pct(last, prev),
        "w1":             _pct(last, _nth_ago(s, 5)),
        "m1":             _pct(last, _nth_ago(s, 21)),
        "y1":             _pct(last, float(s.iloc[0])),
        "hi52":           round(float(s.max()), 2),
        "lo52":           round(float(s.min()), 2),
        "var95_pct":      round(1.645 * sigma * 100, 2),
        "var99_pct":      round(2.326 * sigma * 100, 2),
        "var95_usd":      round(1.645 * sigma * pos, 0),
        "var99_usd":      round(2.326 * sigma * pos, 0),
        "var95_hist_pct": (round(abs(float(np.percentile(rets, 5))) * 100, 2)
                           if len(rets) else None),
    }


def beta_vs_market(stock: pd.Series, market: pd.Series) -> float | None:
    df = pd.concat([stock, market], axis=1).dropna()
    if len(df) < 30:
        return None
    rs = df.iloc[:, 0].pct_change().dropna()
    rm = df.iloc[:, 1].pct_change().dropna()
    j  = pd.concat([rs, rm], axis=1).dropna()
    if len(j) < 30 or j.iloc[:, 1].var() == 0:
        return None
    cov = np.cov(j.iloc[:, 0], j.iloc[:, 1])[0, 1]
    return round(cov / j.iloc[:, 1].var(), 2)


def fundamentals_for(sym: str) -> dict:
    """P/E, div yield, analyst target via yfinance .info."""
    import yfinance as yf
    out = {"pe": "N/A", "div": "N/A", "target": "N/A", "analyst": "N/A", "earnings": "N/A"}
    try:
        info   = yf.Ticker(sym).info
        pe     = info.get("trailingPE")
        dy     = info.get("dividendYield")
        target = info.get("targetMeanPrice")
        out["pe"]      = round(pe, 1) if pe else "N/A"
        if dy:
            dy_pct     = dy if dy > 0.5 else dy * 100
            out["div"] = f"{round(dy_pct, 2)}%"
        out["target"]  = f"${round(target, 2)} (consensus, may lag)" if target else "N/A"
        out["analyst"] = info.get("recommendationKey", "N/A")
    except Exception as e:
        log.warning(f"fundamentals failed {sym}: {e}")
    try:
        cal    = yf.Ticker(sym).get_earnings_dates(limit=4)
        future = cal[cal.index > pd.Timestamp.now(tz=cal.index.tz)]
        if not future.empty:
            out["earnings"] = future.index.min().strftime("%b %d, %Y")
    except Exception:
        pass
    return out


# ---- Macro snapshot -------------------------------------------------------
def macro_snapshot(closes: pd.DataFrame) -> dict:
    """Extract latest macro indicator values from closes DataFrame."""
    def _latest(sym):
        if sym not in closes:
            return None
        s = closes[sym].dropna()
        return float(s.iloc[-1]) if len(s) else None

    def _prev(sym):
        if sym not in closes:
            return None
        s = closes[sym].dropna()
        return float(s.iloc[-2]) if len(s) > 1 else None

    spread   = _latest("T10Y2Y")
    spread_p = _prev("T10Y2Y")
    t5y      = _latest("T5YIEM")
    t10y     = _latest("T10YIEM")
    sofr     = _latest("SOFR")
    ff_lo    = _latest("FF_LOWER")
    ff_hi    = _latest("FF_UPPER")
    dxy      = _latest("DXY_BROAD")
    dxy_p    = _prev("DXY_BROAD")

    return {
        "spread_10y2y":     spread,
        "spread_chg":       round(spread - spread_p, 3) if (spread is not None and spread_p is not None) else None,
        "spread_inverted":  spread is not None and spread < 0,
        "tips_5y":          t5y,
        "tips_10y":         t10y,
        "tips_5y_flag":     t5y is not None and abs(t5y - 2.0) > 0.3,
        "tips_10y_flag":    t10y is not None and abs(t10y - 2.0) > 0.3,
        "sofr":             sofr,
        "ff_lower":         ff_lo,
        "ff_upper":         ff_hi,
        # spike = SOFR more than 5bp above upper bound
        "sofr_spike":       (sofr is not None and ff_hi is not None and sofr > ff_hi + 0.05),
        "dxy":              dxy,
        "dxy_chg":          _pct(dxy, dxy_p) if (dxy and dxy_p) else None,
    }


# ---- Early Warning --------------------------------------------------------
def early_warning(closes: pd.DataFrame) -> dict:
    sig = []
    def add(name, status, meaning):
        sig.append({"name": name, "status": status, "meaning": meaning})

    vix = float(closes["^VIX"].dropna().iloc[-1]) if "^VIX" in closes else None
    if vix is not None:
        st = "GREEN" if vix < 20 else "AMBER" if vix <= 28 else "RED"
        add("VIX (fear gauge)", st,
            f"{vix:.1f} - {'calm' if st=='GREEN' else 'rising stress' if st=='AMBER' else 'high fear'}")

    # 2Y/10Y spread: negative = inverted = recession signal
    if "T10Y2Y" in closes:
        sprd = float(closes["T10Y2Y"].dropna().iloc[-1])
        st   = "RED" if sprd < 0 else "GREEN"
        add("2Y/10Y Yield Spread", st,
            f"{sprd:+.3f}% - {'INVERTED' if st == 'RED' else 'normal'}")

    secs = [c for c in SECTOR_ETFS if c in closes]
    ups  = sum(1 for c in secs if (metrics_for(closes[c]).get("day_change") or 0) > 0)
    if secs:
        ratio = ups / len(secs)
        st = "GREEN" if ratio >= 0.6 else "AMBER" if ratio >= 0.4 else "RED"
        add("Breadth (sectors up)", st,
            f"{ups}/{len(secs)} sectors green - "
            f"{'broad' if st=='GREEN' else 'mixed' if st=='AMBER' else 'narrow'}")

    sp = closes[MKT].dropna()
    if len(sp) >= 50:
        ma    = sp.tail(50).mean()
        above = (sp.iloc[-1] / ma - 1) * 100
        st    = "GREEN" if above <= 10 else "AMBER"
        add("S&P vs 50-day avg", st, f"{above:+.1f}% vs trend")

    if TNX in closes and not closes[TNX].dropna().empty:
        y  = float(closes[TNX].dropna().iloc[-1])
        st = "GREEN" if y < 4.5 else "AMBER" if y <= 5 else "RED"
        add("10Y Treasury yield", st, f"{y:.2f}%")

    bad     = sum(1 for s in sig if s["status"] in ("AMBER", "RED"))
    overall = "WARNING" if bad >= 3 else "CAUTION" if bad == 2 else "HEALTHY"
    return {"signals": sig, "overall": overall, "correction_risk": bad >= 3}


# ---- Top-level builder ----------------------------------------------------
def build_report_data() -> dict:
    closes = fetch_closes()
    mkt    = closes[MKT]

    indices = []
    for sym, name in INDICES.items():
        if sym not in closes:
            continue
        m = metrics_for(closes[sym])
        indices.append({
            "index": name, "closing_price": m.get("price"),
            "day_change": m.get("day_change"), "1_week": m.get("w1"),
            "1_month": m.get("m1"), "1_year": m.get("y1"),
            "52w_high": m.get("hi52"), "52w_low": m.get("lo52"),
        })

    ai_rows = []
    for w in WATCHLIST_AI:
        s = w["symbol"]
        if s not in closes:
            continue
        m = metrics_for(closes[s])
        ai_rows.append({
            "ticker": s, "company": w["name"],
            "price": m.get("price"), "day_change": m.get("day_change"),
            "1_week": m.get("w1"), "1_month": m.get("m1"), "1_year": m.get("y1"),
            "52w_low": m.get("lo52"), "52w_high": m.get("hi52"),
            "beta": beta_vs_market(closes[s], mkt),
        })

    sec = []
    for c, name in SECTOR_ETFS.items():
        if c not in closes:
            continue
        dc = metrics_for(closes[c]).get("day_change")
        if dc is not None:
            sec.append({"name": name, "pct": f"{dc:+.2f}%", "val": dc})
    sec.sort(key=lambda x: x["val"], reverse=True)
    winners = [{"name": s["name"], "pct": s["pct"]} for s in sec[:3]]
    losers  = [{"name": s["name"], "pct": s["pct"]} for s in sec[-2:]]

    candidate_data = {}
    for t in set(r["ticker"] for r in ai_rows):
        if t in closes:
            m = metrics_for(closes[t])
            candidate_data[t] = {"price": m.get("price"), "y1": m.get("y1"),
                                  "beta": beta_vs_market(closes[t], mkt)}

    return {
        "indices":        indices,
        "ai_rows":        ai_rows,
        "winners":        winners,
        "losers":         losers,
        "early_warning":  early_warning(closes),
        "macro":          macro_snapshot(closes),
        "candidate_data": candidate_data,
    }